### ISSUE TITLE
the number difference between the gt density map before and after downsample

### ISSUE THREAD

**Issue by pwr617** [siyuhuang/crowdcount-stackpool#1]
hi~
Can you share how did you deal with the number difference between the gt density map before and after downsample?
Specifically, when I trained the model, I found the number of people (groundtruth) calculated by the ground truth density map before and after downsampling is different. So, if I train with the downsampled gt map, the ground truth number in the final MSE is the sum of downsampled map or the original gt number?
Thank you.

**Comment by siyuhuang** [comment]
@pwr617
 
1. The GT number will be the sum of downsampled map if you set `ImageDataLoader(gt_downsample=True)` whenever training or testing.
2. The sum of density map will be slightly different before and after downsampling due to the interpolation operation in `cv2.resize` (line 54 in src/data_loader.py).

Thanks!
